import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { services, method } from "@/data/services";
import { Action, SectionTitle } from "./Primitives";
export function Manifesto(){return <section className="intro-section wrap" id="approche"><p>VOUS FAIRE REMARQUER.<br/>VOUS FAIRE CHOISIR.<br/><span>VOUS FAIRE CONTACTER.</span><br/>ET CONTINUER À RÉPONDRE.</p><div><h2>Votre communication<br/>doit vous faire avancer.</h2><p>Une vidéo attire l’œil. Une image juste donne confiance. Un site transforme l’envie en contact. Nous relions les points pour construire une présence qui sert votre activité.</p></div></section>}
export function ServicesJourney(){return <section className="services-section wrap"><SectionTitle text="Quatre étapes qui relient nos expertises. Un seul objectif : faire avancer votre activité.">Pas juste visible.<br/>Vraiment choisi.</SectionTitle><div className="service-list">{services.map(s=><Link className="service-row" href={`/services#${s.id}`} key={s.id}><span className="service-number">{s.number}</span><h3>{s.title}</h3><p>{s.description}</p><ArrowUpRight aria-hidden="true"/></Link>)}</div></section>}
export function Laja360Flow(){return <section className="flow-section" id="laja360"><div className="wrap"><div className="flow-heading"><h2>Une agence.<br/><span>Tout le parcours.</span></h2><p>De la première vidéo vue sur Instagram jusqu’au premier message, rendez-vous ou achat.</p></div><ol className="flow-chain">{["CONTENU","SOCIAL","SITE","AGENT IA","CLIENT"].map((t,i)=><li key={t}><span className="flow-order">0{i+1}</span><span>{t}</span>{i<4&&<ArrowUpRight className="flow-arrow" size={24}/>}</li>)}</ol><div className="flow-end"><span>LAJA 360 — LA COMMUNICATION QUI RELIE LES POINTS.</span><Action light href="/contact?besoin=Accompagnement%20360">Construire mon écosystème</Action></div></div></section>}
export function Method(){return <section className="method-section wrap"><SectionTitle text="Du premier échange à la mise en mouvement, chaque étape a son rôle.">De bonnes idées.<br/>Et une vraie méthode.</SectionTitle><ol className="method-list">{method.map((m,i)=><li key={m.title}><span>0{i+1}</span><h3>{m.title}</h3><p>{m.text}</p></li>)}</ol></section>}
export function BeforeAfter(){return <section className="before-after wrap"><div className="before-column"><h2>On connaît<br/>la musique.</h2><p>Des posts quand on a le temps.<br/>Une image qui change à chaque publication.<br/>Des messages qui attendent.</p></div><div className="after-column"><h2>Changeons<br/>le rythme.</h2><p>Une stratégie qui donne le cap.<br/>Des contenus qui se répondent.<br/>Un site et un assistant qui prennent le relais.</p><span>Exemple de parcours — résultats selon votre activité.</span></div></section>}

