"use client";
import { useEffect,useState } from "react";
import { RotateCcw, ArrowUpRight, CheckCheck, MoreVertical, ChevronLeft } from "lucide-react";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Action } from "./Primitives";
const conversations={
restaurant:[{client:true,text:"Bonsoir, vous avez une table pour 4 demain vers 20h30 ?",time:"20:42"},{client:false,text:"Bonsoir ! Je peux préparer votre demande. Préférez-vous l’intérieur ou la terrasse ?",time:"20:42"},{client:true,text:"Terrasse si possible.",time:"20:43"},{client:false,text:"Noté : 4 personnes, demain à 20h30, en terrasse. L’équipe devra confirmer la disponibilité. À quel nom souhaitez-vous faire la demande ?",time:"20:43"}],
boutique:[{client:true,text:"Bonjour ! Vous avez encore cette veste en taille M ?",time:"18:24"},{client:false,text:"Bonjour ! Pouvez-vous préciser le modèle ou sa couleur ? Je préparerai votre question pour l’équipe.",time:"18:24"},{client:true,text:"La veste beige de votre dernier post.",time:"18:25"},{client:false,text:"Merci ! L’équipe pourra vérifier le stock de cette veste en M et vous répondre. Souhaitez-vous aussi connaître les horaires de la boutique ?",time:"18:25"}]
};
export default function WhatsAppDemo({full=false}:{full?:boolean}){
 const [scenario,setScenario]=useState<keyof typeof conversations>("restaurant");const [visible,setVisible]=useState(4);const [run,setRun]=useState(0);
 useEffect(()=>{if(!run||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timers=[1,2,3,4].map((n)=>setTimeout(()=>setVisible(n),n*650));return()=>timers.forEach(clearTimeout)},[run]);
 function replay(){if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setVisible(4);return}setVisible(0);setRun(v=>v+1)}
 return <section className={`whatsapp-section ${full?"whatsapp-full":""}`}><div className="wrap whatsapp-inner"><div className="demo-side"><div className="demo-toolbar"><Tabs value={scenario} onValueChange={v=>{setScenario(v as keyof typeof conversations);setVisible(4)}}><TabsList className="demo-tabs" aria-label="Scénario de démonstration"><TabsTrigger value="restaurant">Restaurant</TabsTrigger><TabsTrigger value="boutique">Boutique</TabsTrigger></TabsList></Tabs><button className="replay" onClick={replay} aria-label="Rejouer la conversation"><RotateCcw size={16}/></button></div><div className="phone"><div className="phone-status"><span>20:43</span><span>DÉMONSTRATION</span></div><div className="chat-header"><ChevronLeft size={20}/><span className="chat-avatar">L.</span><div><strong>Votre entreprise</strong><small>Assistant LAJA · conversation simulée</small></div><MoreVertical size={19}/></div><div className="chat-body"><span className="chat-day">Aujourd’hui</span>{conversations[scenario].slice(0,visible).map((m,i)=><div className={`chat-message ${m.client?"client":"assistant"}`} key={scenario+i}><p>{m.text}</p><span>{m.time}{m.client&&<CheckCheck size={13}/>}</span></div>)}</div><div className="chat-bottom">Exemple illustratif · aucun message envoyé</div></div></div><div className="whatsapp-copy"><h2>Vos clients écrivent<br/>quand ils veulent.<br/><span>Répondez présent.</span></h2><p>Un assistant WhatsApp pour répondre aux premières questions, préciser les besoins et passer le relais à votre équipe.</p><ul><li>Informations et questions fréquentes</li><li>Demandes mieux qualifiées</li><li>Un humain reprend quand il le faut</li></ul><div className="assistant-price"><strong>49 €</strong><span>/ mois</span></div><Action href={full?"/contact?besoin=Assistant%20WhatsApp":"/assistant-whatsapp"}>{full?"Parlons de votre assistant":"Découvrir l’assistant WhatsApp"}</Action><p className="small-note">Fonctions selon configuration. Réservations et disponibilités à confirmer par votre équipe ou par un outil connecté.</p>{full&&<a className="text-link" href="/contact">Une question sur l’intégration ? <ArrowUpRight size={16}/></a>}</div></div></section>
}

