import type { Metadata } from "next";
import PageIntro from "@/components/laja/PageIntro";
import WhatsAppDemo from "@/components/laja/WhatsAppDemo";
import { FinalCTA } from "@/components/laja/Footer";
import { Action } from "@/components/laja/Primitives";
import { site } from "@/data/site";
export const metadata:Metadata={title:"Assistant WhatsApp — 49 €/mois",description:"Répondez aux premières questions de vos clients et qualifiez leurs demandes avec l’assistant WhatsApp LAJA.",alternates:{canonical:"/assistant-whatsapp"}};
export default function Assistant(){return <main id="main"><PageIntro title={<>LE BON MOMENT.<br/><span>C’EST LE LEUR.</span></>}><p>À la fermeture, pendant un service ou entre deux rendez-vous : une question client mérite une première réponse.</p></PageIntro><WhatsAppDemo full/><section className="wrap faq-section"><h2>Un assistant.<br/>Votre équipe aux commandes.</h2><div>{[{q:"Que peut faire l’assistant ?",a:"Présenter les informations que vous lui fournissez, répondre aux questions fréquentes et recueillir les précisions utiles à votre équipe. Son périmètre se définit avec vous."},{q:"Peut-il confirmer une réservation ou un stock ?",a:"Seulement si une connexion à vos outils le permet et a été configurée. Sinon, il prépare la demande et votre équipe confirme. La démonstration de cette page ne consulte aucun stock ni planning réel."},{q:"Un humain peut-il reprendre la conversation ?",a:"Le passage à votre équipe fait partie du parcours à définir. Nous précisons avec vous les situations qui nécessitent une intervention et la manière de transmettre les demandes."},{q:"Que comprend le tarif de 49 €/mois ?",a:"C’est le tarif de l’offre assistant WhatsApp. Le périmètre, les intégrations éventuelles et les conditions sont précisés avant souscription. Aucun paiement n’est déclenché depuis la démonstration."}].map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}<Action href={site.assistantCheckout||"/contact?besoin=Assistant%20WhatsApp"}>Préparer mon assistant — 49 €/mois</Action></div></section><FinalCTA/></main>}

